version: "3"
services:
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  postgres:
    image: postgres:16.2
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  smpt4dev:
    image: rnwood/smtp4dev
    ports:
      - "3000:80"
      - "2525:25"
