# Generated by Django 5.0.2 on 2024-02-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('References', '0002_gamecategory_game_remove_game_game_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='played',
        ),
    ]
