# Generated by Django 5.0.2 on 2024-02-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('References', '0003_remove_game_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamecategory',
            name='game',
            field=models.ManyToManyField(blank=True, null=True, related_name='game_categories', to='References.game'),
        ),
    ]
