# Generated by Django 5.0.2 on 2024-02-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('References', '0004_alter_game_release_date_alter_gamecategory_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_category',
            field=models.ManyToManyField(blank=True, related_name='games', to='References.gamecategory'),
        ),
        migrations.AlterField(
            model_name='gamecategory',
            name='game',
            field=models.ManyToManyField(blank=True, related_name='game_categories', to='References.game'),
        ),
    ]
