# Generated by Django 5.0.3 on 2024-03-17 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('References', '0006_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='images')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='References.reference')),
                ('reference_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_contents', to='References.reference')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='References.reference')),
                ('reference_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_contents', to='References.reference')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
