# Generated by Django 5.0.3 on 2024-03-17 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('References', '0008_remove_image_reference_remove_video_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='reference_video',
            new_name='reference_image',
        ),
    ]
