# Generated by Django 5.0.3 on 2024-03-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('References', '0010_game_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='preview_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
