# Generated by Django 5.0.3 on 2024-03-26 10:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('References', '0011_reference_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='reference',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='References.game'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
